#! /bin/sh

# (no c) S.P. 2014, released under GPLv3 or later.
# All lefts and wrongs reserved.
#
# /etc/init.d/oet1

  case "$1" in
    start)
        echo -n "Oet1 update on startup: "
	conn=`nm-tool | grep "State: connected" | wc -l`
        if [ "$conn" -eq "1" ] 
		then
            cd /usr/local/OET1;
            git pull;
	    cp /usr/local/OET1/scripts/*.sh /usr/local/bin;
	    cp /usr/local/OET1/init.d/oet1 /etc/init.d;
	    chmod a+x /etc/init.d/oet1;
        fi
        ;;
    stop)
        echo -n "Oet1 update on shutdown: "
	conn=`nm-tool | grep "State: connected" | wc -l`
        if [ "$conn" -eq "1" ] 
		then
            cd /usr/local/OET1;
            git pull;
	    cp /usr/local/OET1/scripts/*.sh /usr/local/bin;
	    cp /usr/local/OET1/init.d/oet1 /etc/init.d;
	    chmod a+x /etc/init.d/oet1;
        fi
        echo -n "Reverting home directory's Desktop/OET1lab to initial state"
        /usr/local/bin/oet1-home-revert.sh
        chown -R student.student /home/student/Desktop/OET1lab
        ;;
    *)
        ## If no parameters are given, print which are avaiable.
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
